import type { LessonContent } from '../../types/content'
import { FlowJourney } from '../../components/teaching/FlowJourney'
import { GateJourney } from '../../components/teaching/GateJourney'
import { ParameterLab } from '../../components/teaching/ParameterLab'
import { ProfitBridge } from '../../components/teaching/ProfitBridge'
import { MoneyFlow } from '../../components/teaching/MoneyFlow'
import { EvidenceWall } from '../../components/teaching/EvidenceWall'
import { DecisionBoard } from '../../components/teaching/DecisionBoard'
import { CompareSpace } from '../../components/teaching/CompareSpace'
import { ProductStructure } from '../../components/teaching/ProductStructure'
import { DynamicGraph } from '../../components/teaching/DynamicGraph'
import { componentsForLesson } from '../../data/motherComponentMap'
const ev=[{title:'E1',source:'官方 / 监管 / 平台原始资料',summary:'动态平台、准入、规则与治理信息按开课时间核验。',initial:'support' as const},{title:'E4',source:'真实经营证据',summary:'真实成本、物流、内容与订单用于验证经营判断。',initial:'unknown' as const}]
export function M01M04Scene({lesson}:{lesson:LessonContent}){
 const head=<div className="scene-heading"><div><div className="eyebrow">Interactive Teaching World｜交互教学世界 · {lesson.code}</div><h1>{lesson.title}</h1><p>{lesson.coreStatement}</p></div><div className="status-chip">Interactive Scene｜交互场景</div></div>
 if(lesson.code==='T01-M01-L01')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Product｜商品',note:'从真实商品与供应开始'},{title:'Information｜信息',note:'Listing、内容和用户理解形成信息流'},{title:'Order｜订单',note:'交易把需求转成履约责任'},{title:'Fulfillment｜履约',note:'商品沿物流链交付',exception:'延迟/错货会反向影响售后和健康'},{title:'Money｜资金',note:'结算、费用、汇率后进入到账'}]}/><EvidenceWall items={ev}/></section>
 if(lesson.code==='T01-M01-L03')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['Traffic｜流量','Inventory｜库存','Fulfillment｜履约','Control｜控制','Main Cost｜主要成本']} items={[{name:'Marketplace｜平台店',values:{'Traffic｜流量':'平台+付费/内容','Inventory｜库存':'卖家/平台仓','Fulfillment｜履约':'平台规则内','Control｜控制':'中','Main Cost｜主要成本':'平台/履约/获客'}},{name:'Content Commerce｜内容电商',values:{'Traffic｜流量':'内容/达人/LIVE','Inventory｜库存':'卖家负责','Fulfillment｜履约':'跨境/本地','Control｜控制':'中','Main Cost｜主要成本':'内容/佣金/广告'}},{name:'DTC｜独立站',values:{'Traffic｜流量':'自建获客','Inventory｜库存':'卖家负责','Fulfillment｜履约':'自主组合','Control｜控制':'高','Main Cost｜主要成本':'获客/技术/履约'}}]}/><DecisionBoard options={[{id:'p',title:'平台主导',evidence:'需要平台现成交易基础设施',risk:'平台规则与费用'},{id:'c',title:'内容主导',evidence:'商品可通过内容证明',risk:'内容供给与转化'},{id:'d',title:'自有渠道',evidence:'需要数据和品牌控制',risk:'自建获客成本'}]}/></section>
 if(lesson.code==='T01-M01-L04')return <section className="workbench family-scene">{head}<ProfitBridge/><ParameterLab parameters={[{name:'Selling Price｜售价',min:40,max:180,initial:100},{name:'Refund｜退款',min:0,max:30,initial:5},{name:'Growth｜获客',min:0,max:50,initial:18},{name:'Logistics｜物流',min:5,max:50,initial:16}]} formula={v=>v[0]-34-v[1]-v[2]-v[3]}/><MoneyFlow nodes={[{label:'Customer Payment｜消费者付款',value:100,kind:'income'},{label:'Product｜商品',value:34,kind:'cost'},{label:'Fulfillment｜履约',value:16,kind:'cost'},{label:'Growth｜增长',value:18,kind:'cost'}]}/></section>
 if(lesson.code==='T01-M02-L02')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['Language｜语言','Compliance｜合规','Fulfillment｜履约','Returns｜退货']} items={[{name:'United States｜美国',values:{'Language｜语言':'英语为主','Compliance｜合规':'按品类/联邦+州核验','Fulfillment｜履约':'直发/本地/平台仓','Returns｜退货':'纳入成本模型'}},{name:'United Kingdom｜英国',values:{'Language｜语言':'英语','Compliance｜合规':'英国规则独立核验','Fulfillment｜履约':'本地体验重要','Returns｜退货':'消费者规则核验'}},{name:'European Union｜欧盟',values:{'Language｜语言':'多语言/国家化','Compliance｜合规':'欧盟+成员国/品类','Fulfillment｜履约':'跨国与本地组合','Returns｜退货':'消费者权利纳入设计'}}]}/><GateJourney gates={[{title:'Product Rule｜产品规则',note:'按品类核验'},{title:'Label / Claims｜标签/宣称',note:'按目标司法辖区核验'},{title:'Tax / Consumer｜税务/消费者',note:'进入专项规则核验'},{title:'Fulfillment｜履约',note:'时效与退货进入经济模型'}]}/></section>
 if(lesson.code==='T01-M02-L03')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['Platform Mix｜平台','Language｜语言','Payment｜支付','Logistics｜物流','Localization｜本地化']} items={[{name:'Indonesia｜印尼',values:{'Platform Mix｜平台':'TikTok Shop / Shopee等','Language｜语言':'印尼语','Payment｜支付':'按当前市场数据核验','Logistics｜物流':'岛屿履约差异','Localization｜本地化':'宗教/文化/价格带'}},{name:'Malaysia｜马来西亚',values:{'Platform Mix｜平台':'TikTok Shop / Shopee / Lazada等','Language｜语言':'马来语/英语等','Payment｜支付':'按当前市场数据核验','Logistics｜物流':'区域配送条件','Localization｜本地化':'多语言/文化'}},{name:'Vietnam｜越南',values:{'Platform Mix｜平台':'TikTok Shop / Shopee等','Language｜语言':'越南语','Payment｜支付':'按当前市场数据核验','Logistics｜物流':'本地配送条件','Localization｜本地化':'价格/内容表达'}}]}/><EvidenceWall items={ev}/></section>
 if(lesson.code==='T01-M02-L04')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Region｜区域',note:'先确定研究范围'},{title:'Country｜国家',note:'下钻具体司法辖区与平台'},{title:'Product｜商品',note:'加入商品条件'},{title:'Evidence｜证据',note:'核验规则、价格、物流和内容'},{title:'Decision｜判断',note:'保留已知/未知，不用区域平均替代国家事实'}]}/><DecisionBoard options={[{id:'gcc',title:'GCC国家研究',evidence:'国家级规则+商品证据',risk:'认证/进口要求差异'},{id:'jk',title:'日韩研究',evidence:'语言/品质/平台结构',risk:'本地化深度'},{id:'latam',title:'拉美国家研究',evidence:'支付/物流/税费',risk:'国家差异'}]}/></section>
 if(lesson.code==='T01-M03-L01')return <section className="workbench family-scene">{head}<ProductStructure/><FlowJourney steps={[{title:'Legal Entity｜企业主体',note:'谁承担经营责任'},{title:'Seller Identity｜卖家身份',note:'平台如何识别经营者'},{title:'Market / Site｜市场/站点',note:'卖到哪里'},{title:'Entry Route｜入驻路径',note:'以何种开放路径进入'},{title:'Fulfillment｜履约',note:'库存从哪里发、如何交付'}]}/></section>
 if(lesson.code==='T01-M03-L02')return <section className="workbench family-scene">{head}<GateJourney gates={[{title:'Local Entity｜当地主体',note:'主体真实性'},{title:'Address｜地址',note:'经营地址证据'},{title:'Tax｜税务',note:'按市场规则核验'},{title:'Settlement｜结算',note:'收款条件'},{title:'Warehouse / Return｜仓储/退货',note:'实际运营能力'}]}/><EvidenceWall items={ev}/></section>
 if(lesson.code==='T01-M03-L03')return <section className="workbench family-scene">{head}<GateJourney gates={[{title:'Confirmed｜已确认',note:'当前官方证据明确支持'},{title:'Conditional｜条件开放',note:'满足明确条件后成立'},{title:'Research Needed｜待研究',note:'证据不足，不能推断'},{title:'Not Applicable｜不适用',note:'当前条件下不适用'}]}/><p className="component-callout">Last Verified｜最后核验必须跟随动态跨境开放政策保存。</p></section>
 if(lesson.code==='T01-M03-L04')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['Upfront Inventory｜前置库存','Speed｜时效','Cash｜现金占用','Returns｜退货','Best Use｜适用阶段']} items={[{name:'Direct Shipping｜跨境直发',values:{'Upfront Inventory｜前置库存':'低','Speed｜时效':'较长','Cash｜现金占用':'较低','Returns｜退货':'复杂','Best Use｜适用阶段':'测试/长尾'}},{name:'Local Stock｜本地库存',values:{'Upfront Inventory｜前置库存':'高','Speed｜时效':'快','Cash｜现金占用':'高','Returns｜退货':'本地处理','Best Use｜适用阶段':'稳定SKU'}},{name:'Hybrid｜混合履约',values:{'Upfront Inventory｜前置库存':'分层','Speed｜时效':'分层','Cash｜现金占用':'可调','Returns｜退货':'需双路径','Best Use｜适用阶段':'测试→放量'}}]}/><ParameterLab parameters={[{name:'International Logistics｜国际物流',min:5,max:60,initial:22},{name:'Local Inventory｜本地库存',min:0,max:300,initial:80},{name:'Lead Time｜补货提前期',min:3,max:60,initial:20,unit:'天'}]}/></section>
 if(lesson.code==='T01-M04-L01')return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'tiktok',label:'TikTok｜内容场'},{id:'shop',label:'TikTok Shop｜交易场'},{id:'seller',label:'Seller Center｜卖家中心'},{id:'product',label:'Product｜商品'},{id:'order',label:'Order｜订单'}]} edges={[{from:'tiktok',to:'shop'},{from:'shop',to:'product'},{from:'product',to:'order'},{from:'seller',to:'product'},{from:'seller',to:'order'}]}/></section>
 if(lesson.code==='T01-M04-L02')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Discovery｜发现',note:'短视频/达人/LIVE/搜索/商城'},{title:'Product Entry｜商品入口',note:'商品锚点/商品卡'},{title:'PDP｜商品详情页',note:'理解价格、评价、配送和商品事实'},{title:'Cart / Checkout｜购物车/结算',note:'库存、价格与信任继续影响决策'},{title:'Order｜订单',note:'交易转成履约责任'}]}/></section>
 if(lesson.code==='T01-M04-L03')return <section className="workbench family-scene">{head}<ParameterLab parameters={[{name:'Organic｜自然内容',min:0,max:100,initial:55},{name:'Creator/Affiliate｜达人/联盟',min:0,max:100,initial:35},{name:'Ads｜广告',min:0,max:100,initial:20},{name:'LIVE｜直播',min:0,max:100,initial:15}]} /><p className="component-callout">放大机制不会修复未验证的商品、内容、PDP或单位经济；它也可能放大错误。</p></section>
 return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'product',label:'Product Issue｜商品问题'},{id:'fulfill',label:'Fulfillment Issue｜履约异常'},{id:'refund',label:'Refund / Complaint｜退款/投诉'},{id:'health',label:'Store Health｜店铺健康'},{id:'restriction',label:'Restriction｜功能限制'}]} edges={[{from:'product',to:'refund'},{from:'fulfill',to:'refund'},{from:'refund',to:'health'},{from:'health',to:'restriction'}]}/><GateJourney gates={[{title:'Fact｜事实',note:'先确认异常事实'},{title:'Evidence｜证据',note:'定位责任节点'},{title:'Correction｜纠正',note:'执行可验证修复'},{title:'Recovery｜恢复',note:'复核状态是否恢复'}]}/></section>
}
