import type { LessonContent } from '../../types/content'
import { GateJourney } from '../../components/teaching/GateJourney'
import { FlowJourney } from '../../components/teaching/FlowJourney'
import { ParameterLab } from '../../components/teaching/ParameterLab'
import { ProfitBridge } from '../../components/teaching/ProfitBridge'
import { MoneyFlow } from '../../components/teaching/MoneyFlow'
import { PortfolioBoard } from '../../components/teaching/PortfolioBoard'
import { ProductStructure } from '../../components/teaching/ProductStructure'
import { AssetLineage } from '../../components/teaching/AssetLineage'
import { EvidenceWall } from '../../components/teaching/EvidenceWall'
import { DecisionBoard } from '../../components/teaching/DecisionBoard'
import { TimelineScrubber } from '../../components/teaching/TimelineScrubber'
import { DynamicGraph } from '../../components/teaching/DynamicGraph'
import { CompareSpace } from '../../components/teaching/CompareSpace'
import { ContentRemix } from '../../components/teaching/ContentRemix'

const evidence=[{title:'E1',source:'官方 / 监管 / 平台原始资料',summary:'动态规则、字段、准入和费用应按开课时间核验。',initial:'support' as const},{title:'E4',source:'真实业务证据',summary:'报价、样品、成本、素材、订单或经营记录用于验证课堂判断。',initial:'unknown' as const}]
const decisions=[{id:'a',title:'继续推进',evidence:'关键条件已验证',risk:'仍需保留动态规则核验'},{id:'b',title:'补证据后再推进',evidence:'存在关键未知',risk:'避免把假设当事实'},{id:'c',title:'停止当前路径',evidence:'触发硬风险或事实冲突',risk:'重新选择可行方案'}]

export function M05M08Scene({lesson}:{lesson:LessonContent}){
 const head=<div className="scene-heading"><div><div className="eyebrow">Interactive Teaching Lab｜交互教学实验 · {lesson.code}</div><h1>{lesson.title}</h1><p>{lesson.coreStatement}</p></div><div className="status-chip">Decision Lab｜判断实验</div></div>
 if(lesson.code==='T01-M05-L01')return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'owner',label:'主体',note:'经营责任与关键资产所有权'},{id:'identity',label:'身份',note:'人员/主体身份验证'},{id:'device',label:'设备',note:'稳定、合法、可恢复'},{id:'network',label:'网络',note:'稳定连接与安全边界'},{id:'account',label:'账号',note:'关键经营账号'},{id:'permission',label:'权限',note:'最小必要权限'},{id:'recovery',label:'恢复',note:'交接与恢复机制'}]} edges={[{from:'owner',to:'identity',label:'验证'},{from:'owner',to:'account',label:'控制'},{from:'account',to:'permission',label:'授权'},{from:'device',to:'account',label:'访问'},{from:'network',to:'device',label:'连接'},{from:'account',to:'recovery',label:'恢复'}]}/><GateJourney gates={[{title:'Identity｜身份',note:'主体与人员身份可验证'},{title:'Device / Network｜设备与网络',note:'稳定、合法、可恢复'},{title:'Account Ownership｜账号所有权',note:'关键资产由经营主体控制'},{title:'Permission｜权限',note:'最小必要权限并可交接'}]}/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M05-L02')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Market｜市场',note:'明确目标市场'},{title:'Seller Origin｜卖家来源',note:'明确主体来源'},{title:'Entry Route｜入驻路线',note:'按当前官方条件核验'},{title:'Site / Fulfillment｜站点与履约',note:'经营路线保持一致'},{title:'Language｜语言',note:'商品与内容语言匹配市场'}]}/><DecisionBoard options={decisions}/></section>
 if(lesson.code==='T01-M05-L03')return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'entity',label:'法律主体',note:'注册名称/编号'},{id:'rep',label:'代表人',note:'身份与授权'},{id:'address',label:'地址',note:'经营资料一致'},{id:'warehouse',label:'仓库',note:'实际履约地点'},{id:'return',label:'退货',note:'真实退货路径'},{id:'settlement',label:'结算',note:'收款主体关系'}]} edges={[{from:'entity',to:'rep',label:'授权'},{from:'entity',to:'address',label:'登记'},{from:'entity',to:'settlement',label:'主体关系'},{from:'address',to:'warehouse',label:'经营'},{from:'warehouse',to:'return',label:'售后'}]}/><GateJourney gates={[{title:'Legal Entity｜法律主体',note:'名称与注册信息一致'},{title:'Representative｜代表人',note:'身份与授权可验证'},{title:'Address｜地址',note:'经营资料保持事实一致'},{title:'Warehouse / Return｜仓库与退货',note:'实际运营信息可证明'},{title:'Settlement｜结算',note:'收款主体与资料关系清楚'}]}/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M05-L04')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Account｜账号',note:'基础账号就绪'},{title:'Permission｜权限',note:'角色权限完成'},{title:'Warehouse｜仓库',note:'发货地址配置'},{title:'Return｜退货',note:'退货路径配置'},{title:'Logistics｜物流',note:'履约方式可用'},{title:'Settlement｜结算',note:'收款配置完成'},{title:'READY FOR PRODUCT｜商品就绪',note:'进入商品工作阶段'}]}/></section>
 if(lesson.code==='T01-M06-L02')return <section className="workbench family-scene">{head}<EvidenceWall items={[{title:'Market｜市场',source:'E1/E2/E3',summary:'市场规模、平台页面与研究证据',initial:'unknown'},{title:'Product｜商品',source:'E2/E4',summary:'商品结构、评价、样品与测试',initial:'unknown'},{title:'User｜用户',source:'E2/E4',summary:'需求表达、反馈与真实购买行为',initial:'unknown'},{title:'Content｜内容',source:'E2/E4',summary:'内容表现与商品承接',initial:'unknown'},{title:'Business Test｜经营测试',source:'E4',summary:'报价、样品与小规模订单验证',initial:'unknown'}]}/><DecisionBoard options={decisions}/></section>
 if(lesson.code==='T01-M06-L03')return <section className="workbench family-scene">{head}<GateJourney gates={[{title:'Platform｜平台',note:'商品是否允许销售'},{title:'Certification｜认证',note:'是否存在强制认证'},{title:'Safety / Tech｜安全与技术',note:'电气、无线、安全等要求'},{title:'Label / Package｜标签包装',note:'目标市场标签和包装要求'},{title:'IP / Claims｜知识产权与宣称',note:'商标、版权、功效宣称'},{title:'Shipping｜运输',note:'危险品、尺寸、重量等限制'}]}/></section>
 if(lesson.code==='T01-M06-L04')return <section className="workbench family-scene">{head}<PortfolioBoard items={[{id:'p1',title:'Candidate A｜候选A'},{id:'p2',title:'Candidate B｜候选B'},{id:'p3',title:'Candidate C｜候选C'},{id:'p4',title:'Candidate D｜候选D'}]}/><DecisionBoard options={decisions}/></section>
 if(lesson.code==='T01-M07-L01')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['Price / MOQ｜价格/起订','QC｜质量控制','Lead Time｜交期','Customization｜定制','Compliance｜合规','Scale｜扩量']} items={[{name:'Factory Direct｜工厂直采',values:{'Price / MOQ｜价格/起订':'价格潜力高 / MOQ需谈','QC｜质量控制':'可深入','Lead Time｜交期':'生产周期','Customization｜定制':'强','Compliance｜合规':'需共同验证','Scale｜扩量':'强'}},{name:'Trader / 1688｜贸易/平台货源',values:{'Price / MOQ｜价格/起订':'灵活','QC｜质量控制':'需额外验证','Lead Time｜交期':'通常较快','Customization｜定制':'有限','Compliance｜合规':'证据质量不一','Scale｜扩量':'视供应链'}},{name:'Local Overseas｜海外本地',values:{'Price / MOQ｜价格/起订':'成本通常较高','QC｜质量控制':'可现场/本地','Lead Time｜交期':'补货快','Customization｜定制':'有限至中','Compliance｜合规':'本地证据仍需核验','Scale｜扩量':'视本地供给'}}]}/><DecisionBoard options={[{id:'own',title:'Own / Integrated｜自有/整合供应',evidence:'控制力较高',risk:'资产与组织投入'},{id:'factory',title:'Factory Direct｜工厂直采',evidence:'规格与量产可深入协同',risk:'MOQ、沟通、QC'},{id:'cluster',title:'Industrial Cluster｜产业带',evidence:'供应密度高',risk:'供应商筛选'},{id:'local',title:'Local Overseas｜海外本地供应',evidence:'补货与本地响应',risk:'成本与选择范围'}]}/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M07-L02')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Requirement｜需求',note:'冻结询价输入'},{title:'RFQ｜询价',note:'形成可比较报价'},{title:'Supplier Compare｜供应商比较',note:'价格之外比较MOQ/QC/交期'},{title:'Sample｜样品',note:'验证真实商品'},{title:'Spec Freeze｜规格冻结',note:'形成量产依据'},{title:'QC｜质量检查',note:'Critical / Major / Minor',exception:'发现Critical问题：停止放行并进入纠正'},{title:'Mass Production｜量产',note:'按冻结规格生产'},{title:'Replenishment｜补货',note:'连接销售与库存'}]}/></section>
 if(lesson.code==='T01-M07-L03')return <section className="workbench family-scene">{head}<ProfitBridge/><ParameterLab parameters={[{name:'Selling Price｜售价',min:40,max:180,initial:100},{name:'Logistics｜物流',min:5,max:50,initial:16},{name:'Creator/Ads｜达人/广告',min:0,max:50,initial:18},{name:'Refund｜退款',min:0,max:30,initial:5}]} formula={v=>v[0]-34-v[1]-v[2]-v[3]}/><MoneyFlow nodes={[{label:'Net Sales｜净销售',value:100,kind:'income'},{label:'Product｜商品',value:34,kind:'cost'},{label:'Logistics｜物流',value:16,kind:'cost'},{label:'Growth｜增长',value:18,kind:'cost'}]}/></section>
 if(lesson.code==='T01-M07-L04')return <section className="workbench family-scene">{head}<ParameterLab parameters={[{name:'Price｜售价',min:50,max:150,initial:100},{name:'Demand｜需求',min:10,max:200,initial:80},{name:'Lead Time｜交期',min:3,max:60,initial:20,unit:'天'},{name:'Inventory｜库存',min:0,max:300,initial:120}]} /><TimelineScrubber steps={[{time:'D0',title:'采购付款',note:'现金先流出'},{time:'D20',title:'到仓可售',note:'库存转为可售'},{time:'D35',title:'形成订单',note:'利润可能已产生，但现金尚未全部回收'},{time:'D50',title:'平台结算',note:'进入结算周期'},{time:'D55',title:'银行到账',note:'完成本轮现金回收'}]}/></section>
 if(lesson.code==='T01-M08-L01')return <section className="workbench family-scene">{head}<ProductStructure/><GateJourney gates={[{title:'Category｜类目',note:'类目与商品事实匹配'},{title:'Attributes｜属性',note:'关键属性完整'},{title:'Variant｜变体',note:'变体维度真实且有意义'},{title:'SKU｜库存单元',note:'与物理库存一一对应'}]}/></section>
 if(lesson.code==='T01-M08-L02')return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'facts',label:'商品事实',note:'规格/材质/功能/尺寸'},{id:'core',label:'核心商品词',note:'用户在找什么'},{id:'use',label:'用途词',note:'为什么/何时使用'},{id:'attr',label:'属性词',note:'尺寸/材质/适配'},{id:'intent',label:'搜索意图',note:'把词组织成需求簇'},{id:'listing',label:'Listing',note:'标题/卖点/详情承接'}]} edges={[{from:'facts',to:'attr',label:'事实约束'},{from:'core',to:'intent',label:'聚类'},{from:'use',to:'intent',label:'聚类'},{from:'attr',to:'intent',label:'聚类'},{from:'intent',to:'listing',label:'表达'},{from:'facts',to:'listing',label:'真实性'}]}/><ContentRemix/><FlowJourney steps={[{title:'Facts｜事实',note:'规格、材质、功能、尺寸'},{title:'Intent｜意图',note:'核心商品词、用途词、属性词'},{title:'Language｜语言',note:'目标市场自然表达'},{title:'Listing｜商品信息',note:'形成标题、卖点与详情'}]}/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M08-L03')return <section className="workbench family-scene">{head}<AssetLineage/><GateJourney gates={[{title:'Truth｜真实性',note:'商品事实未改变'},{title:'Consistency｜一致性',note:'图文视频互相一致'},{title:'Source｜来源',note:'素材来源可追溯'},{title:'Rights｜权利',note:'版权/肖像/品牌授权可核验'}]}/></section>
 return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Configuration｜配置',note:'价格/库存/配送/SKU'},{title:'Review｜审核',note:'进入平台审核状态'},{title:'Published｜发布',note:'发布不等于正确'},{title:'Front-end QA｜前台质检',note:'以消费者视角检查真实展示',exception:'发现价格、库存、配送或素材错误：返回配置修正'}]}/><EvidenceWall items={evidence}/></section>
}
