import type { LessonContent } from '../../types/content'
import { FlowJourney } from '../../components/teaching/FlowJourney'
import { GateJourney } from '../../components/teaching/GateJourney'
import { ParameterLab } from '../../components/teaching/ParameterLab'
import { ProfitBridge } from '../../components/teaching/ProfitBridge'
import { MoneyFlow } from '../../components/teaching/MoneyFlow'
import { AssetLineage } from '../../components/teaching/AssetLineage'
import { ContentRemix } from '../../components/teaching/ContentRemix'
import { EvidenceWall } from '../../components/teaching/EvidenceWall'
import { DecisionBoard } from '../../components/teaching/DecisionBoard'
import { FunnelDiagnosis } from '../../components/teaching/FunnelDiagnosis'
import { PriorityRoom } from '../../components/teaching/PriorityRoom'
import { TimelineScrubber } from '../../components/teaching/TimelineScrubber'
import { CompareSpace } from '../../components/teaching/CompareSpace'
import { DynamicGraph } from '../../components/teaching/DynamicGraph'
import { VideoAnalyzer } from '../../components/teaching/VideoAnalyzer'
import { IncrementalityLab } from '../../components/teaching/IncrementalityLab'
import { SettlementBridge } from '../../components/teaching/SettlementBridge'

const evidence=[{title:'E1',source:'官方 / 监管 / 平台原始资料',summary:'动态功能、规则、归因和结算口径需按开课时间核验。',initial:'support' as const},{title:'E4',source:'真实业务数据',summary:'内容、达人、广告、订单、物流和财务结果用于验证经营判断。',initial:'unknown' as const}]
const decisions=[{id:'test',title:'Small Test｜小额测试',evidence:'基础条件成立但仍需验证',risk:'控制预算和暴露'},{id:'scale',title:'Scale Ready｜可放大',evidence:'商品、创意、转化与经济模型已有证据',risk:'继续观察边际效果'},{id:'hold',title:'Hold｜暂缓',evidence:'关键条件未知或冲突',risk:'先补证据'}]

export function M09M12Scene({lesson}:{lesson:LessonContent}){
 const head=<div className="scene-heading"><div><div className="eyebrow">Integrated Teaching Lab｜综合教学实验 · {lesson.code}</div><h1>{lesson.title}</h1><p>{lesson.coreStatement}</p></div><div className="status-chip">课堂产出｜{lesson.output}</div></div>
 if(lesson.code==='T01-M09-L01')return <section className="workbench family-scene">{head}<VideoAnalyzer duration={26} beats={[{start:0,end:3,label:'Hook｜钩子',purpose:'赢得继续观看的机会'},{start:3,end:7,label:'Problem / Desire｜问题/欲望',purpose:'让用户理解为什么与自己有关'},{start:7,end:14,label:'Demo｜演示',purpose:'展示商品如何工作'},{start:14,end:21,label:'Proof｜证明',purpose:'降低结果与商品事实的不确定性'},{start:21,end:26,label:'CTA｜行动引导',purpose:'把意图导向下一步动作'}]}/><FlowJourney steps={[{title:'Ignore → Notice｜忽略→注意',note:'Hook先赢得继续观看的机会'},{title:'Understand｜理解',note:'问题/欲望与商品关系变清楚'},{title:'Believe｜相信',note:'Demo与Proof降低不确定性'},{title:'Want｜想要',note:'场景与结果建立购买动机'},{title:'Act｜行动',note:'CTA把意图导向商品/购买动作'}]}/></section>\n if(lesson.code==='T01-M09-L02')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['核心证明','适用场景','主要风险']} items={[{name:'Direct Demo｜直接演示',values:{'核心证明':'动作/结果','适用场景':'效果可视化商品','主要风险':'演示与实物不一致'}},{name:'Before/After｜前后对比',values:{'核心证明':'变化','适用场景':'可验证改善','主要风险':'夸大效果'}},{name:'UGC｜用户表达',values:{'核心证明':'体验/信任','适用场景':'需要社会证明','主要风险':'授权与真实性'}}]}/><DecisionBoard options={decisions}/></section>
 if(lesson.code==='T01-M09-L03')return <section className="workbench family-scene">{head}<AssetLineage/><FlowJourney steps={[{title:'Real Assets｜真实资产',note:'锁定商品事实'},{title:'AI Scene / Video｜AI场景/视频',note:'重构表达，不改变商品事实'},{title:'TTS / Subtitle｜配音/字幕',note:'生成语言表达'},{title:'Localization｜本地化',note:'目标市场语义复核'},{title:'Human Review｜人工审核',note:'检查事实、语言、权利和平台规则',exception:'发现事实偏移：阻断发布并返回源资产修正'}]}/></section>
 if(lesson.code==='T01-M09-L04')return <section className="workbench family-scene">{head}<ContentRemix/><AssetLineage/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M10-L01')return <section className="workbench family-scene">{head}<DynamicGraph nodes={[{id:'merchant',label:'商家',note:'商品/佣金/样品/目标'},{id:'product',label:'商品',note:'证明方式与经济空间'},{id:'creator',label:'达人',note:'受众/内容/信任'},{id:'content',label:'内容',note:'商品表达与证明'},{id:'consumer',label:'消费者',note:'需求与购买反馈'},{id:'result',label:'经营结果',note:'订单/退款/贡献'}]} edges={[{from:'merchant',to:'product',label:'供给'},{from:'merchant',to:'creator',label:'合作'},{from:'product',to:'content',label:'证明'},{from:'creator',to:'content',label:'表达'},{from:'content',to:'consumer',label:'触达'},{from:'consumer',to:'result',label:'交易'},{from:'result',to:'merchant',label:'反馈'}]}/><CompareSpace dimensions={['Audience｜受众','Content｜内容','Proof｜证明','Commercial Fit｜商业适配']} items={[{name:'Creator A｜达人A',values:{'Audience｜受众':'高匹配','Content｜内容':'演示型','Proof｜证明':'强','Commercial Fit｜商业适配':'待报价'}},{name:'Creator B｜达人B',values:{'Audience｜受众':'广但分散','Content｜内容':'娱乐型','Proof｜证明':'弱','Commercial Fit｜商业适配':'高佣金'}}]}/><DecisionBoard options={decisions}/></section>
 if(lesson.code==='T01-M10-L02')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Product｜商品',note:'确认适合达人推广'},{title:'Open Collaboration｜开放合作',note:'扩大达人发现范围'},{title:'Target Collaboration｜定向合作',note:'针对重点达人邀约'},{title:'Sample｜样品',note:'样品属于获客投资'},{title:'Content｜内容',note:'观察出片与商品表达'},{title:'Order / Return｜订单/退款',note:'回到真实经营结果'}]}/><ParameterLab parameters={[{name:'Commission｜佣金',min:0,max:40,initial:15,unit:'%'},{name:'Sample Cost｜样品成本',min:0,max:50,initial:10},{name:'Contribution Before Affiliate｜联盟前贡献',min:10,max:70,initial:35}]} formula={v=>v[2]-v[0]-v[1]/5}/></section>
 if(lesson.code==='T01-M10-L03')return <section className="workbench family-scene">{head}<GateJourney gates={[{title:'Product｜商品',note:'商品已有基础验证'},{title:'Creative｜创意',note:'存在有效内容信号'},{title:'Conversion｜转化',note:'商品页可以承接流量'},{title:'Economics｜经济模型',note:'付费后仍有经营空间'},{title:'Data｜数据',note:'关键事件和口径可读'},{title:'Budget｜预算',note:'测试预算和停止条件明确'}]}/><IncrementalityLab/></section>
 if(lesson.code==='T01-M10-L04')return <section className="workbench family-scene">{head}<GateJourney gates={[{title:'Product｜商品',note:'适合持续演示'},{title:'Content｜内容',note:'有足够脚本与素材'},{title:'Inventory｜库存',note:'能承受直播放量'},{title:'Service｜服务',note:'客服与售后可承接'},{title:'Team / Tech｜团队/技术',note:'真人或AI辅助有人负责'},{title:'Economics｜经济',note:'直播成本进入利润模型'}]}/><CompareSpace dimensions={['Interaction｜互动','Production｜生产效率','Exception Handling｜异常处理','Oversight｜人工监督','Best Use｜适用方式']} items={[{name:'Human LIVE｜真人直播',values:{'Interaction｜互动':'强','Production｜生产效率':'受排班影响','Exception Handling｜异常处理':'现场判断强','Oversight｜人工监督':'天然存在','Best Use｜适用方式':'高互动/复杂问答'}},{name:'AI-assisted LIVE｜AI辅助直播',values:{'Interaction｜互动':'受系统能力限制','Production｜生产效率':'高','Exception Handling｜异常处理':'需要人工兜底','Oversight｜人工监督':'必须明确','Best Use｜适用方式':'标准化表达/辅助生产'}},{name:'Hybrid｜混合直播',values:{'Interaction｜互动':'强','Production｜生产效率':'中高','Exception Handling｜异常处理':'人工+系统','Oversight｜人工监督':'持续','Best Use｜适用方式':'规模化且保留人工判断'}}]}/><DecisionBoard options={[{id:'human',title:'Human LIVE｜真人直播',evidence:'强互动和人工判断',risk:'人力与排班'},{id:'ai',title:'AI-assisted｜AI辅助',evidence:'提升生产效率',risk:'规则、事实与异常监督'},{id:'hybrid',title:'Hybrid｜混合',evidence:'人工监督+自动化辅助',risk:'系统复杂度'}]}/></section>
 if(lesson.code==='T01-M11-L01')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Order Created｜订单创建',note:'订单进入系统'},{title:'Payment｜支付',note:'支付状态确认'},{title:'Picking｜拣货',note:'库存转入履约'},{title:'Packing｜包装',note:'完成包装与标签',exception:'错货/破损：阻断交接并返工'},{title:'Handover｜交接',note:'交给承运环节'},{title:'Transit｜运输',note:'追踪物流状态'},{title:'Delivered｜签收',note:'完成妥投'},{title:'After-sales｜售后',note:'退款、退货或评价'}]}/><TimelineScrubber steps={[{time:'T0',title:'创建',note:'检查支付和库存'},{time:'T1',title:'履约',note:'拣货包装交接'},{time:'T2',title:'运输',note:'Tracking持续更新'},{time:'T3',title:'签收/售后',note:'订单并未在发货时结束'}]}/></section>
 if(lesson.code==='T01-M11-L03')return <section className="workbench family-scene">{head}<FlowJourney steps={[{title:'Product Facts｜商品事实',note:'名称、材质、功能、数量、价值、原产地'},{title:'HS Candidate｜HS候选',note:'按事实建立分类核验路径'},{title:'CI / PL｜商业发票/装箱单',note:'文件事实保持一致'},{title:'Customs｜海关核验',note:'按目的国实际要求处理'}]}/><GateJourney gates={[{title:'Classification｜分类',note:'最终HS按实际商品核验'},{title:'Value｜价值',note:'真实申报价值'},{title:'Documents｜文件',note:'单证一致'},{title:'Restrictions｜限制',note:'检查进口/运输限制'}]}/></section>
 if(lesson.code==='T01-M11-L04')return <section className="workbench family-scene">{head}<SettlementBridge/></section>
 if(lesson.code==='T01-M12-L01')return <section className="workbench family-scene">{head}<FunnelDiagnosis stages={[{label:'Exposure｜曝光',value:10000},{label:'Click｜点击',value:720},{label:'Product View｜商品浏览',value:610},{label:'Add｜加购',value:105},{label:'Order｜订单',value:48},{label:'Retained｜退款后保留',value:41}]}/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M12-L02')return <section className="workbench family-scene">{head}<CompareSpace dimensions={['上层信号','经营结果','关键成本/风险']} items={[{name:'Content｜内容',values:{'上层信号':'观看/停留/互动','经营结果':'点击/订单','关键成本/风险':'制作成本/错配流量'}},{name:'Creator｜达人',values:{'上层信号':'出片/点击','经营结果':'归因成交/退款','关键成本/风险':'样品/佣金'}},{name:'Ads｜广告',values:{'上层信号':'曝光/点击','经营结果':'归因成交/净销售','关键成本/风险':'广告成本/增量不确定'}},{name:'LIVE｜直播',values:{'上层信号':'在线/互动','经营结果':'商品点击/订单','关键成本/风险':'人力/库存/售后'}}]}/><IncrementalityLab/><EvidenceWall items={evidence}/></section>
 if(lesson.code==='T01-M12-L03')return <section className="workbench family-scene">{head}<ProfitBridge/><MoneyFlow nodes={[{label:'GMV｜成交总额',value:130,kind:'income'},{label:'Refund / Cancel｜退款/取消',value:15,kind:'cost'},{label:'COGS｜商品成本',value:34,kind:'cost'},{label:'Logistics｜物流',value:16,kind:'cost'},{label:'Growth｜增长',value:22,kind:'cost'}]}/><SettlementBridge/><p className="component-callout">P&amp;L｜损益与 Cash｜现金必须并行观察：盈利发生时间与现金到账时间可以不同。</p></section>
 return <section className="workbench family-scene">{head}<PriorityRoom items={[{title:'商品点击率下降',evidence:'连续两周期CTR下降',impact:'高',action:'检查入口素材与商品匹配，单变量测试'},{title:'退款率上升',evidence:'退款原因集中在规格理解',impact:'高',action:'修正Listing/内容证明并复核商品质量'},{title:'达人样品效率低',evidence:'出片率低且目标受众错配',impact:'中高',action:'收紧达人筛选与样品条件'},{title:'库存周转变慢',evidence:'在库天数持续增加',impact:'中',action:'调整补货和促销节奏'}]}/><TimelineScrubber steps={[{time:'Week 1',title:'Diagnose｜诊断',note:'确认Top 3问题和证据'},{time:'Week 2',title:'Test｜测试',note:'执行小范围单变量动作'},{time:'Week 3',title:'Validate / Scale｜验证/放大',note:'依据结果继续或停止'},{time:'Week 4',title:'Review｜复盘',note:'形成下一周期经营决策'}]}/></section>
}
