export type EvidenceLevel='E1'|'E2'|'E3'|'E4'|'E5'
export type EvidenceVerdict='supported'|'contradicted'|'conflicted'|'unknown'
export type KnowledgeDepth='L1'|'L2'|'L3'|'L4'
export type TeachingPhase='intro'|'observe'|'explore'|'decide'|'test'|'compare'|'reflect'|'complete'
export interface KnowledgeNode{id:string;titleZh:string;titleEn?:string;depth:KnowledgeDepth;summaryZh:string;whyZh?:string;howZh?:string;boundaryZh?:string;relatedIds?:string[]}
export interface EvidenceItem{id:string;titleZh:string;level:EvidenceLevel;verdict:EvidenceVerdict;sourceType:'official'|'observed'|'research'|'business'|'simulation';sourceZh:string;publishedAt?:string;lastVerifiedAt?:string;supportsZh?:string;contradictsZh?:string;confidence?:number}
export interface TeachingVariable{id:string;labelZh:string;labelEn?:string;kind:'number'|'percentage'|'currency'|'choice'|'boolean'|'unknown';min?:number;max?:number;step?:number;defaultValue:number|string|boolean|null;unit?:string;sourceStatus:'known'|'estimated'|'unknown';impacts:string[]}
export interface TeachingCase{id:string;titleZh:string;kind:'case'|'counterexample'|'simulation';contextZh:string;evidenceIds?:string[];variables?:Record<string,number|string|boolean|null>;promptZh:string;revealZh:string}
export interface PresenterStep{id:string;phase:TeachingPhase;titleZh:string;instructionZh:string;focusIds?:string[];revealIds?:string[];durationHintSec?:number}
export interface LessonTeachingSpec{lessonCode:string;knowledgeTree:KnowledgeNode[];defaultVisibleIds:string[];evidence:EvidenceItem[];variables:TeachingVariable[];cases:TeachingCase[];presenterSteps:PresenterStep[];researchGaps?:Array<{id:string;priority:'P0'|'P1'|'P2';type:'research'|'case'|'visual'|'video'|'rule'|'compliance';descriptionZh:string}>}