import {useState} from 'react';
import {NavLink,Outlet,useLocation} from 'react-router-dom';
import {routeStages,workshopMachines,coachingMachines} from '../data/t01';
import {ModeBadge} from '../components/common/ModeBadge';
import {useAppState} from '../state/AppState';
import {getOverallProgress,getStageProgress} from '../domain/progress';
export default function AppShell(){
  const[open,setOpen]=useState(false);const{state}=useAppState();const location=useLocation();const overall=getOverallProgress(routeStages,state,workshopMachines,coachingMachines);const stageIndex=routeStages.findIndex(s=>location.pathname.includes(s.id));const current=stageIndex>=0?routeStages[stageIndex]:null;
  return <div className="app"><aside className={'sidebar '+(open?'open':'')}><div className="brand"><div className="brandMark">T</div><div><b>T01 Commerce Lab</b><span className="subtle brandSub">TikTok 0→1 实战系统</span></div></div><ModeBadge/><div className="sideProgress"><div><span>经营闭环进度</span><b>{overall.pct}%</b></div><div className="progress"><span style={{width:`${overall.pct}%`}}/></div><small>{overall.done}/{overall.total} 个能力节点完成</small></div><nav className="stageNav"><NavLink to="/t01" end onClick={()=>setOpen(false)}><span className="navIndex">⌂</span><span>课程总览</span></NavLink>{routeStages.map((s,i)=>{const p=getStageProgress(s,state,workshopMachines,coachingMachines);return <NavLink key={s.id} to={'/t01/'+s.id} onClick={()=>setOpen(false)}><span className="navIndex">{String(i+1).padStart(2,'0')}</span><span className="navText"><b>{s.label}</b><small>{p.done}/{p.total} · {p.pct}%</small><i><em style={{width:`${p.pct}%`}}/></i></span></NavLink>})}</nav><div className="sideFoot"><NavLink to="/t01/tools" className="sideUtility">工具工作区 <span>15</span></NavLink><NavLink to="/t01/results" className="sideUtility">经营档案 <span>10</span></NavLink><NavLink to="/t01/progress" className="sideUtility">进度地图 <span>{overall.pct}%</span></NavLink><NavLink to="/t01/instructor" className="sideUtility">讲师控制台 <span>↗</span></NavLink></div></aside><main className="main"><header className="topbar"><button className="btn secondary mobileOnly" onClick={()=>setOpen(!open)}>菜单</button><div className="topContext"><span className="eyebrow">TIKTOK SHOP OPERATING LAB</span><b>{current?`${String(stageIndex+1).padStart(2,'0')} · ${current.label}`:'TikTok Shop 经营主线'}</b></div><div className="topbarRight"><span className="topRuleState"><i/>动态规则需核验</span><span className="versionPill">2.8</span></div></header><div className="content"><Outlet/><div className="footerNote">教学数据默认保存在本浏览器；模拟数据必须标识。动态平台规则以上课前官方核验为准。</div></div></main>{open&&<button className="mobileScrim" onClick={()=>setOpen(false)} aria-label="关闭菜单"/>}</div>
}
