import {useState,type ReactNode} from 'react';
import {safeRatio} from '../../domain/calculations';

const Status=({tone='ok',children}:{tone?:'ok'|'warn'|'bad';children:ReactNode})=><span className={`status ${tone}`}>{children}</span>;
const Range=({label,value,set,min=0,max=100,step=1,suffix=''}:{label:string;value:number;set:(v:number)=>void;min?:number;max?:number;step?:number;suffix?:string})=><label className="rangeField"><span>{label}<b>{value}{suffix}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>;
const Toggle=({label,on,set}:{label:string;on:boolean;set:(v:boolean)=>void})=><button className={`toggle ${on?'on':''}`} onClick={()=>set(!on)}><span>{on?'✓':'·'}</span>{label}</button>;

function RouteDecision(){const[entity,setEntity]=useState('中国公司');const[warehouse,setWarehouse]=useState('中国直发');const[returns,setReturns]=useState(false);const[language,setLanguage]=useState(false);const gaps=[!returns&&'缺少稳定退货方案',!language&&'缺少目标市场内容/客服语言能力'].filter(Boolean);return <Lab title="经营路线决策器" note="不是市场排名，而是把现有条件反推为第一条可执行路线。"><div className="controlRow"><label>主体<select value={entity} onChange={e=>setEntity(e.target.value)}><option>中国公司</option><option>目标市场本地主体</option><option>尚未确定</option></select></label><label>履约<select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option>中国直发</option><option>本地仓</option><option>海外仓</option></select></label></div><div className="toggleRow"><Toggle label="具备退货能力" on={returns} set={setReturns}/><Toggle label="具备本地化语言能力" on={language} set={setLanguage}/></div><Result tone={gaps.length?'warn':'ok'} title={gaps.length?'需补条件':'可进入启动验证'}>{entity} · {warehouse}{gaps.length?<ul>{gaps.map(x=><li key={x}>{x}</li>)}</ul>:<p>下一步进入目标站点当期准入与KYC核验。</p>}</Result></Lab>}

function PermissionMatrix(){const roles=['商品运营','客服','广告','财务'];const perms=['商品','订单/售后','广告','结算'];const[map,setMap]=useState<Record<string,string>>({});const correct:Record<string,string>={'商品运营':'商品','客服':'订单/售后','广告':'广告','财务':'结算'};return <Lab title="最小权限矩阵" note="把岗位拖成“所有人都是管理员”并不等于协作顺畅。"><div className="matrix">{roles.map(r=><div className="matrixRow" key={r}><b>{r}</b>{perms.map(p=><button key={p} className={map[r]===p?'selected':''} onClick={()=>setMap(m=>({...m,[r]:p}))}>{p}</button>)}<span>{map[r]?map[r]===correct[r]?<Status>匹配</Status>:<Status tone="warn">需复核</Status>:<Status tone="warn">未配置</Status>}</span></div>)}</div></Lab>}

function KycChecker(){const fields=['主体名称','注册地址','负责人姓名','银行账户名'];const[data,setData]=useState<Record<string,string>>({});const base='Globera Trading Ltd';const mismatch=fields.filter((f,i)=>data[f]&&i<2&&data[f]!==base);return <Lab title="KYC资料一致性检查" note="重点不是“有文件”，而是跨文件关键字段是否真实一致。"><div className="formGrid">{fields.map((f,i)=><label key={f}><span>{f}</span><input value={data[f]||''} placeholder={i<2?base:'填写真实字段'} onChange={e=>setData(d=>({...d,[f]:e.target.value}))}/></label>)}</div><Result tone={mismatch.length?'bad':'ok'} title={mismatch.length?'发现不一致字段':'当前未发现示例冲突'}>{mismatch.length?`请核对：${mismatch.join('、')}`:'仍需按目标站点官方要求核验资料类型、有效期和补件要求。'}</Result></Lab>}

function ProductFit(){const[demand,setDemand]=useState(60),[show,setShow]=useState(70),[margin,setMargin]=useState(45),[fulfill,setFulfill]=useState(75),[risk,setRisk]=useState(25);const score=Math.round((demand+show+margin+fulfill+(100-risk))/5);return <Lab title="TikTok商品六维适配实验台" note="不是给商品打神秘总分，而是观察哪个变量正在拖垮测试可行性。"><div className="rangeGrid"><Range label="需求信号" value={demand} set={setDemand}/><Range label="内容展示性" value={show} set={setShow}/><Range label="利润空间" value={margin} set={setMargin}/><Range label="履约可行性" value={fulfill} set={setFulfill}/><Range label="风险强度" value={risk} set={setRisk}/></div><Meter value={score}/><Result tone={score>=70?'ok':score>=50?'warn':'bad'} title={score>=70?'可进入首轮验证':score>=50?'需要补证据':'暂不进入首测'}>重点检查最低项，而不是只看综合分。</Result></Lab>}

function EvidenceBoard(){const items=['同类SKU近30天持续成交','一条视频播放很高但无商品点击','多个Creator重复展示同一卖点','价格远高于同类且无明显证明','样本只有昨天一天'];const[state,setState]=useState<Record<string,string>>({});const columns=['支持','反对','未知'];return <Lab title="商品信号证据板" note="把“看起来不错”拆成支持、反对和未知证据。"><div className="evidenceGrid">{items.map(x=><div className="evidenceCard" key={x}><b>{x}</b><div>{columns.map(c=><button className={state[x]===c?'selected':''} onClick={()=>setState(s=>({...s,[x]:c}))} key={c}>{c}</button>)}</div></div>)}</div><Result tone={Object.keys(state).length===items.length?'ok':'warn'} title="待验证问题">{Object.keys(state).length===items.length?'已完成一轮信号分类；下一步写出测试假设和停止条件。':'还有证据未分类，不能提前下结论。'}</Result></Lab>}

function RiskSpotter(){const risks=[['“7天治愈痘痘”','宣称'],['包装出现他人注册商标','IP'],['普通服装展示真实尺码','正常'],['食品无必要标签信息','合规'],['图片把1件商品变成3件套','误导']];const[picks,setPicks]=useState<Record<number,boolean>>({});return <Lab title="Listing风险点识别" note="先找明显红线，再把不确定项送进专业核验。"><div className="riskList">{risks.map(([text,type],i)=><button key={text} onClick={()=>setPicks(p=>({...p,[i]:!p[i]}))} className={picks[i]?'picked':''}><span>{picks[i]?'✓':'○'}</span><b>{text}</b>{picks[i]&&<Status tone={type==='正常'?'ok':'warn'}>{type}</Status>}</button>)}</div></Lab>}

function SkuBuilder(){const[color,setColor]=useState(['Black','Ivory']);const[size,setSize]=useState(['S','M']);const add=(kind:'color'|'size')=>{if(kind==='color')setColor(c=>[...c,`Color ${c.length+1}`]);else setSize(s=>[...s,`Size ${s.length+1}`])};return <Lab title="SKU / 变体树编辑器" note="所有变体必须属于同一个真实商品，不用变体伪造不同商品。"><div className="skuTree"><div><b>颜色</b>{color.map(x=><span className="chip" key={x}>{x}</span>)}<button onClick={()=>add('color')}>＋</button></div><div><b>尺寸</b>{size.map(x=><span className="chip" key={x}>{x}</span>)}<button onClick={()=>add('size')}>＋</button></div></div><div className="kpiRow"><Kpi label="SKU组合" value={String(color.length*size.length)}/><Kpi label="消费者选择层" value="2"/><Kpi label="库存独立追踪" value="是"/><Kpi label="结构" value={color.length*size.length<=12?'清晰':'需简化'}/></div></Lab>}

function ClaimLocker(){const[facts,setFacts]=useState({material:true,size:true,origin:false,award:false});const claim='100%真丝 · 110×110cm · 法国设计大奖 · 意大利制造';const tokens=[['100%真丝','material'],['110×110cm','size'],['法国设计大奖','award'],['意大利制造','origin']] as const;return <Lab title="事实锁定器" note="文案可以优化表达，但不能优化出不存在的商品事实。"><div className="toggleRow">{Object.entries({material:'材质已核验',size:'尺寸已核验',origin:'产地已核验',award:'奖项已核验'}).map(([k,l])=><Toggle key={k} label={l} on={(facts as any)[k]} set={v=>setFacts(f=>({...f,[k]:v}))}/>)}</div><div className="claimPreview">{tokens.map(([t,k])=><span className={(facts as any)[k]?'safe':'unsafe'} key={t}>{t}</span>)}</div><Result tone={tokens.every(([,k])=>(facts as any)[k])?'ok':'warn'} title="文案QA">{tokens.filter(([,k])=>!(facts as any)[k]).map(([t])=>t).join('、')||'全部有证据'} {tokens.some(([,k])=>!(facts as any)[k])&&'需要删除、改写或补证据。'}</Result></Lab>}

function AssetSequencer(){const initial=['白底主图','核心卖点图','尺寸/规格','使用场景','细节证明'];const[items,setItems]=useState(initial);const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=items.length)return;const a=[...items];[a[i],a[j]]=[a[j],a[i]];setItems(a)};return <Lab title="商品素材移动端排序器" note="排序不是美术偏好，而是首屏先解决识别，再解释差异和证明。"><div className="phonePreview">{items.map((x,i)=><div className="assetTile" key={x}><span>{i+1}</span><b>{x}</b><div><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button></div></div>)}</div></Lab>}

function UnitContribution(){const[price,setPrice]=useState(39),[discount,setDiscount]=useState(3),[product,setProduct]=useState(10),[ship,setShip]=useState(8),[commission,setCommission]=useState(5),[ads,setAds]=useState(6);const revenue=price-discount,contrib=revenue-product-ship-commission-ads;return <Lab title="价格—履约—佣金联动实验" note="测试前先知道每出一单大致还能留下多少贡献。"><div className="rangeGrid"><Range label="标价" value={price} set={setPrice} min={10} max={100} suffix=""/><Range label="卖家折扣" value={discount} set={setDiscount} min={0} max={20}/><Range label="商品成本" value={product} set={setProduct} min={1} max={40}/><Range label="履约/物流" value={ship} set={setShip} min={1} max={30}/><Range label="佣金预留" value={commission} set={setCommission} min={0} max={20}/><Range label="广告预留" value={ads} set={setAds} min={0} max={30}/></div><div className="kpiRow"><Kpi label="预计实收" value={revenue.toFixed(2)}/><Kpi label="单位贡献" value={contrib.toFixed(2)}/><Kpi label="贡献率" value={(safeRatio(contrib,revenue)*100).toFixed(1)+'%'}/><Kpi label="首测判断" value={contrib>5?'可继续':'需调整'}/></div></Lab>}

function ContentFunnel(){const[views,setViews]=useState(10000),[impressions,setImpressions]=useState(3200),[clicks,setClicks]=useState(210),[orders,setOrders]=useState(9);const ctr=safeRatio(clicks,impressions),ctor=safeRatio(orders,clicks);const issue=impressions/views<.15?'内容到商品曝光弱':ctr<.05?'商品点击弱':ctor<.03?'PDP/价格/信任弱':'漏斗基础健康';return <Lab title="内容成交漏斗诊断" note="播放量只是最上游；真正要看商品曝光、点击和订单。"><div className="funnelInputs"><InputNum label="Video Views" value={views} set={setViews}/><InputNum label="Product Impressions" value={impressions} set={setImpressions}/><InputNum label="Product Clicks" value={clicks} set={setClicks}/><InputNum label="SKU Orders" value={orders} set={setOrders}/></div><div className="kpiRow"><Kpi label="商品曝光率" value={(impressions/views*100).toFixed(1)+'%'}/><Kpi label="CTR" value={(ctr*100).toFixed(1)+'%'}/><Kpi label="CTOR" value={(ctor*100).toFixed(1)+'%'}/><Kpi label="诊断" value={issue}/></div></Lab>}

function IdeaGenerator(){const[benefit,setBenefit]=useState('快速展示变化');const[scene,setScene]=useState('早晨出门前');const[pain,setPain]=useState('步骤太麻烦');const angles=[`问题钩子：${pain}？30秒看${benefit}`,`场景反差：${scene}前后对比`,`证明型：先给结果，再展示${benefit}过程`,`挑战型：只用一个动作解决“${pain}”`];return <Lab title="从商品卖点到内容选题" note="同一个卖点至少要能生成不同内容角度，而不是改几个形容词。"><div className="formGrid"><label><span>核心卖点</span><input value={benefit} onChange={e=>setBenefit(e.target.value)}/></label><label><span>用户场景</span><input value={scene} onChange={e=>setScene(e.target.value)}/></label><label><span>痛点</span><input value={pain} onChange={e=>setPain(e.target.value)}/></label></div><div className="ideaGrid">{angles.map((x,i)=><div className="ideaCard" key={x}><span>ANGLE {i+1}</span><b>{x}</b></div>)}</div></Lab>}

function ScriptBuilder(){const[parts,setParts]=useState(['Hook','Problem','Demo','Proof','Offer','CTA']);const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=parts.length)return;const a=[...parts];[a[i],a[j]]=[a[j],a[i]];setParts(a)};return <Lab title="脚本与镜头节奏编排器" note="结构可以变化，但每个镜头都应承担明确的成交任务。"><div className="scriptTrack">{parts.map((p,i)=><div className="scriptBlock" key={p}><span>{i+1}</span><b>{p}</b><small>{['0–2s','2–5s','5–10s','10–14s','14–18s','18–21s'][i]}</small><div><button onClick={()=>move(i,-1)}>←</button><button onClick={()=>move(i,1)}>→</button></div></div>)}</div></Lab>}

function PublishChecklist(){const items=['商品链接已挂载','商业内容披露已检查','字幕/语言本地化完成','商品事实与画面一致','封面/首帧可识别商品','发布后记录Video Analytics'];const[done,setDone]=useState<Record<string,boolean>>({});const n=items.filter(x=>done[x]).length;return <Lab title="可购物内容发布闸门" note="成片不是终点；商品链接、披露、发布和数据回看才组成经营闭环。"><div className="checkGrid">{items.map(x=><Toggle key={x} label={x} on={!!done[x]} set={v=>setDone(d=>({...d,[x]:v}))}/>)}</div><Meter value={Math.round(n/items.length*100)}/><Result tone={n===items.length?'ok':'warn'} title={n===items.length?'可以进入发布/模拟发布':'还有发布前置未完成'}>{n}/{items.length} 项完成</Result></Lab>}

function AffiliateFlow(){const[step,setStep]=useState(0);const steps=['商品进入Affiliate','Open/Target选择','Creator接受合作','样品/无样品','Creator发布内容','订单/GMV回传','佣金与复盘'];return <Lab title="Creator / Affiliate成交链路" note="达人不是“找到就结束”，合作要一直追到内容与经营结果。"><div className="flowStepper">{steps.map((x,i)=><button className={i<=step?'done':''} onClick={()=>setStep(i)} key={x}><span>{i+1}</span>{x}</button>)}</div><Result title={`当前：${steps[step]}`}>{step<steps.length-1?'下一步：'+steps[step+1]:'进入Creator分层复盘与下一轮合作。'}</Result></Lab>}

function CreatorScore(){const[match,setMatch]=useState(75),[audience,setAudience]=useState(65),[shopping,setShopping]=useState(70),[consistency,setConsistency]=useState(55);const total=Math.round(match*.3+audience*.25+shopping*.3+consistency*.15);return <Lab title="Creator筛选与匹配实验" note="粉丝数不直接等于商品匹配度。"><div className="rangeGrid"><Range label="类目匹配" value={match} set={setMatch}/><Range label="受众匹配" value={audience} set={setAudience}/><Range label="购物内容质量" value={shopping} set={setShopping}/><Range label="内容稳定性" value={consistency} set={setConsistency}/></div><Meter value={total}/><Result tone={total>=75?'ok':total>=55?'warn':'bad'} title={total>=75?'A档优先触达':total>=55?'B档观察':'C档暂缓'}>要求学员写出“为什么”，不能只提交分数。</Result></Lab>}

function CommissionLab(){const[price,setPrice]=useState(45),[baseCost,setBaseCost]=useState(20),[commission,setCommission]=useState(15),[sample,setSample]=useState(8);const comm=price*commission/100,remain=price-baseCost-comm-sample;return <Lab title="佣金 / 样品经济账" note="高佣金不是独立增长策略，必须和单位经济账一起看。"><div className="rangeGrid"><Range label="售价" value={price} set={setPrice} min={10} max={120}/><Range label="基础成本" value={baseCost} set={setBaseCost} min={1} max={80}/><Range label="佣金率" value={commission} set={setCommission} min={0} max={50} suffix="%"/><Range label="样品摊销" value={sample} set={setSample} min={0} max={30}/></div><div className="kpiRow"><Kpi label="达人佣金" value={comm.toFixed(2)}/><Kpi label="剩余贡献" value={remain.toFixed(2)}/><Kpi label="佣金占售价" value={commission+'%'}/><Kpi label="合作判断" value={remain>5?'可继续':'经济账过紧'}/></div></Lab>}

function AdReadiness(){const items=['PDP已通过QA','库存与履约稳定','已有可用内容素材','单位经济账可承受广告','明确测试目的和停止条件'];const[done,setDone]=useState<Record<string,boolean>>({});const n=items.filter(x=>done[x]).length;return <Lab title="广告就绪五道门" note="GMV Max不是修复烂商品、烂PDP和烂素材的魔法按钮。"><div className="checkGrid">{items.map(x=><Toggle key={x} label={x} on={!!done[x]} set={v=>setDone(d=>({...d,[x]:v}))}/>)}</div><Result tone={n===5?'ok':n>=3?'warn':'bad'} title={n===5?'可以进入基础启动':n>=3?'先补缺口再投':'当前不建议启动'}>{n}/5 道门通过</Result></Lab>}

function LiveLoop(){const steps=['开场定位','Pin商品','问题/场景','Demo展示','Proof证明','Offer','互动问答','CTA','下一商品/再循环'];const[active,setActive]=useState(0);return <Lab title="LIVE商品成交循环" note="直播不是连续说话，而是一轮轮可重复、可复盘的商品成交循环。"><div className="liveLoop">{steps.map((x,i)=><button onClick={()=>setActive(i)} className={active===i?'active':''} key={x}><span>{i+1}</span>{x}</button>)}</div><Result title={steps[active]}>完成当前段后记录商品点击、CTR、订单与GMV，而不是只记录在线人数。</Result></Lab>}

function OrderSla(){const[type,setType]=useState('Seller Shipping'),[hours,setHours]=useState(24),[tracking,setTracking]=useState(true);const risk=hours>48||!tracking;return <Lab title="订单履约SLA模拟" note="具体SLA按站点和当期政策核验，这里训练的是状态判断。"><div className="controlRow"><label>Shipping Type<select value={type} onChange={e=>setType(e.target.value)}><option>Seller Shipping</option><option>TikTok Shipping</option><option>Fulfilled by TikTok / 当期能力</option></select></label><label>距订单产生<input type="number" value={hours} onChange={e=>setHours(Number(e.target.value))}/> 小时</label></div><Toggle label="已有有效Tracking/LSP信息" on={tracking} set={setTracking}/><Result tone={risk?'warn':'ok'} title={risk?'出现履约风险信号':'当前基础履约状态可继续'}>{risk?'检查当期发货SLA、Tracking有效性及VTR/LDR/OTDR/SFCR影响。':`${type}：继续按当前站点要求完成交接并追踪状态。`}</Result></Lab>}

function AfterSales(){const[caseType,setCaseType]=useState('物流延迟');const decisions:Record<string,string>= {'物流延迟':'先核对Tracking与承运商状态，再决定补发/退款/解释','买家取消':'先确认订单状态与当前可取消节点','商品破损':'收集证据→责任判断→退款/退货/补发','与描述不符':'回看Listing事实→处理售后→同步修正商品页'};return <Lab title="售后情景决策器" note="后台动作、客户沟通和店铺健康影响必须一致。"><div className="caseTabs">{Object.keys(decisions).map(x=><button className={caseType===x?'active':''} onClick={()=>setCaseType(x)} key={x}>{x}</button>)}</div><Result title={caseType}>{decisions[caseType]}。具体时限和责任口径按当期站点政策核验。</Result></Lab>}

function HealthDashboard(){const[ahr,setAhr]=useState(92),[sps,setSps]=useState(82),[late,setLate]=useState(3),[valid,setValid]=useState(96);const issue=late>5?'延迟履约优先处理':valid<95?'有效Tracking优先处理':ahr<80?'Account Health风险需定位':sps<75?'Shop Performance需定位':'暂无明显示例风险';return <Lab title="Shop Health根因定位台" note="AHR、SPS和履约指标不是一个分数；版本和阈值必须按当前站点核验。"><div className="rangeGrid"><Range label="AHR示例" value={ahr} set={setAhr}/><Range label="SPS示例" value={sps} set={setSps}/><Range label="Late Dispatch示例" value={late} set={setLate} max={15} suffix="%"/><Range label="Valid Tracking示例" value={valid} set={setValid}/></div><Result tone={issue.includes('暂无')?'ok':'warn'} title="当前诊断">{issue}</Result></Lab>}

function SettlementLab(){const[gmv,setGmv]=useState(1000),[sellerDiscount,setSellerDiscount]=useState(80),[refund,setRefund]=useState(60),[platform,setPlatform]=useState(45),[affiliate,setAffiliate]=useState(120),[ads,setAds]=useState(150),[cogs,setCogs]=useState(300),[ship,setShip]=useState(110);const settlement=gmv-sellerDiscount-refund-platform-affiliate;const contribution=settlement-ads-cogs-ship;return <Lab title="GMV → Settlement → 经营贡献" note="平台GMV、结算金额和最终经营利润是三个不同层级。"><div className="rangeGrid compact"><Range label="GMV" value={gmv} set={setGmv} max={3000}/><Range label="卖家折扣" value={sellerDiscount} set={setSellerDiscount} max={500}/><Range label="退款" value={refund} set={setRefund} max={500}/><Range label="平台费用" value={platform} set={setPlatform} max={300}/><Range label="Affiliate" value={affiliate} set={setAffiliate} max={500}/><Range label="广告" value={ads} set={setAds} max={800}/><Range label="COGS" value={cogs} set={setCogs} max={1000}/><Range label="履约" value={ship} set={setShip} max={500}/></div><div className="kpiRow"><Kpi label="GMV" value={gmv.toFixed(0)}/><Kpi label="Settlement示例" value={settlement.toFixed(0)}/><Kpi label="经营贡献" value={contribution.toFixed(0)}/><Kpi label="贡献率" value={(safeRatio(contribution,gmv)*100).toFixed(1)+'%'}/></div></Lab>}

export default function LessonSceneLab({id}:{id:string}){switch(id){
 case'T01-C02':return <RouteDecision/>;case'T01-C03':return <PermissionMatrix/>;case'T01-C04':return <KycChecker/>;case'T01-C06':return <ProductFit/>;case'T01-C07':return <EvidenceBoard/>;case'T01-C08':return <RiskSpotter/>;case'T01-C09':return <SkuBuilder/>;case'T01-C10':return <ClaimLocker/>;case'T01-C11':return <AssetSequencer/>;case'T01-C12':return <UnitContribution/>;case'T01-C13':return <ContentFunnel/>;case'T01-C15':return <IdeaGenerator/>;case'T01-C16':return <ScriptBuilder/>;case'T01-C17':return <PublishChecklist/>;case'T01-C18':return <AffiliateFlow/>;case'T01-C19':return <CreatorScore/>;case'T01-C20':return <CommissionLab/>;case'T01-C21':return <AdReadiness/>;case'T01-C23':return <LiveLoop/>;case'T01-C24':return <OrderSla/>;case'T01-C25':return <AfterSales/>;case'T01-C26':return <HealthDashboard/>;case'T01-C28':return <SettlementLab/>;default:return null}}

function Lab({title,note,children}:{title:string;note:string;children:ReactNode}){return <div className="card sceneLab"><div className="eyebrow">INTERACTIVE LAB｜互动实验</div><h3>{title}</h3><p className="subtle">{note}</p><div className="sceneBody">{children}</div></div>}
function Result({tone='ok',title,children}:{tone?:'ok'|'warn'|'bad';title:string;children:ReactNode}){return <div className={`resultBox ${tone}`}><b>{title}</b><div>{children}</div></div>}
function Meter({value}:{value:number}){return <div className="meter"><div><span>综合状态</span><b>{value}</b></div><div className="progress"><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="kpi"><span className="subtle">{label}</span><b>{value}</b></div>}
function InputNum({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label><span>{label}</span><input type="number" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
