import type {CSSProperties} from 'react';
import {Link} from 'react-router-dom';
import {routeStages,allLessons,workshopMachines,coachingMachines} from '../../data/t01';
import {useAppState} from '../../state/AppState';
import {getOverallProgress,getStageProgress,isLessonDone} from '../../domain/progress';
import {resultReadiness} from '../../domain/resultReadiness';
import DataFlowRail from '../../components/learning/DataFlowRail';
const resultIds=Array.from({length:10},(_,i)=>`T01-R${String(i+1).padStart(2,'0')}`);
export default function CourseHome(){
  const{state}=useAppState();const overall=getOverallProgress(routeStages,state,workshopMachines,coachingMachines);const next=allLessons.find(x=>!isLessonDone(state.lessonStatus[x.code]))||allLessons[allLessons.length-1];const nextStage=routeStages.findIndex(s=>s.course_ids.includes(next.code))+1;
  const readyResults=resultIds.filter(id=>resultReadiness(id,state,workshopMachines,coachingMachines).abilityReady).length;
  const activeCases=coachingMachines.filter(m=>{const cur=state.coachingState[m.code]||m.initial_state;const terminal=Boolean(m.states.find(s=>s.key===cur)?.terminal);const c=state.coachingCases[m.code];return !terminal&&(cur!==m.initial_state||c?.paused||c?.severity==='attention'||c?.severity==='blocked')}).length;
  return <div><section className="hero homeHero"><div className="homeHeroMain"><div className="eyebrow">T01 · TIKTOK COMMERCE OPERATING LAB</div><h1>不是跨境百科。<br/><span>把第一个 TikTok Shop 经营闭环跑出来。</span></h1><p>经营路线 → Shop就绪 → SKU → Listing → 内容 → Creator/Affiliate → GMV Max → LIVE → 订单 → 数据/P&L → 下一轮30天。</p><div className="actionStack section"><Link className="btn" to={`/t01/course/${next.code.toLowerCase()}`}>继续：{next.code} {next.title}</Link><Link className="btn secondary" to="/t01/progress">查看经营进度</Link>{activeCases>0&&<Link className="btn secondary attentionBtn" to="/t01/progress">{activeCases} 个真实案件待继续</Link>}</div></div><div className="homeProgressDial"><div className="dial" style={{'--pct':`${overall.pct}%`} as CSSProperties}><div><b>{overall.pct}%</b><span>经营闭环</span></div></div><small>{overall.done}/{overall.total} 个能力节点</small></div></section><section className="homeStats"><div><span>核心课</span><b>{allLessons.length}</b><small>每课必须有操作或判断</small></div><div><span>实操工作坊</span><b>{workshopMachines.length}</b><small>任务台 + 证据 + 质量闸门</small></div><div><span>真实案件</span><b>{activeCases}</b><small>审核、达人、数据、订单持续推进</small></div><div><span>里程碑就绪</span><b>{readyResults}/10</b><small><Link to="/t01/results">进入毕业经营档案 →</Link></small></div></section><section className="section"><div className="sectionHeading"><div><span className="eyebrow">DATA FLOW｜经营数据链</span><h2>前一个经营动作的结果，会成为后一个动作的输入</h2></div></div><DataFlowRail/></section><section className="section"><div className="sectionHeading"><div><span className="eyebrow">OPERATING ROADMAP｜经营路线</span><h2>9 个阶段不是目录，而是一条可追踪的经营流水线</h2></div><Link to="/t01/results" className="btn secondary">打开毕业经营档案</Link></div><div className="roadmap">{routeStages.map((s,i)=>{const p=getStageProgress(s,state,workshopMachines,coachingMachines);return <Link className={`roadmapCard ${p.pct===100?'done':''}`} key={s.id} to={'/t01/'+s.id}><div className="roadmapNo">{String(i+1).padStart(2,'0')}</div><div className="roadmapBody"><div className="roadmapTop"><b>{s.label}</b><span>{p.pct}%</span></div><p>{s.course_ids.length}门核心课 · {s.workshop_ids.length}个工作坊{s.coaching_ids.length?` · ${s.coaching_ids.length}个陪跑`:''}</p><div className="progress"><span style={{width:`${p.pct}%`}}/></div><div className="roadmapMeta"><span>课程 {p.courseDone}/{s.course_ids.length}</span><span>工作坊 {p.workshopDone}/{s.workshop_ids.length}</span>{s.coaching_ids.length>0&&<span>陪跑 {p.coachingDone}/{s.coaching_ids.length}</span>}</div></div><span className="roadmapArrow">→</span></Link>})}</div></section></div>
}
