import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import type {WorkshopMachine,WorkspaceEvidence} from '../../domain/types';
import {useAppState} from '../../state/AppState';
import {workshopBlueprints} from './workshopBlueprints';
import {getUpstreamSeed} from '../../domain/dataFlow';

const now=()=>new Date().toISOString();
export default function WorkshopWorkbench({machine,current}:{machine:WorkshopMachine;current:string}){
 const{state,dispatch}=useAppState();const bp=workshopBlueprints[machine.code];const ws=state.workshopWorkspace[machine.code]||{values:{},checks:{},branchFlags:{},notes:'',evidence:[],updatedAt:''};
 const[eType,setEType]=useState<WorkspaceEvidence['type']>('截图');const[eTitle,setETitle]=useState('');const[eSource,setESource]=useState('');const[eNotes,setENotes]=useState('');
 const seed=getUpstreamSeed(machine.code,state);const seedKey=JSON.stringify(seed);
 useEffect(()=>{for(const [key,value] of Object.entries(seed)){if(value&&!ws.values[key])dispatch({type:'WORKSHOP_VALUE',id:machine.code,payload:{key,value}})}},[machine.code,seedKey]);
 const reviewSignals=machine.code==='T01-W11'?[
  ['SKU',`${state.workshopWorkspace['T01-W03']?.values.sku||'—'} · 单位贡献 ${state.workshopWorkspace['T01-W03']?.values.unitContribution||'—'}`],
  ['内容',`CTR ${state.workshopWorkspace['T01-W06']?.values.ctr||'—'} · CTOR ${state.workshopWorkspace['T01-W06']?.values.ctor||'—'} · ${state.workshopWorkspace['T01-W06']?.values.next||''}`],
  ['达人',`候选 ${state.workshopWorkspace['T01-W07']?.values.pool||'—'} · A档 ${state.workshopWorkspace['T01-W07']?.values.priority||'—'} · ${state.workshopWorkspace['T01-W07']?.values.outreach||''}`],
  ['广告',`${state.workshopWorkspace['T01-W08']?.values.type||'—'} · ${state.workshopWorkspace['T01-W08']?.values.decision||'—'}`],
  ['履约',`${state.workshopWorkspace['T01-W10']?.values.case||'—'} · ${state.workshopWorkspace['T01-W10']?.values.health||''}`]
 ]:[];
 const required=bp?.fields.filter(f=>f.required)||[];const fieldReady=required.every(f=>String(ws.values[f.key]||'').trim().length>0);const checkReady=bp?bp.checks.every((_,i)=>ws.checks[String(i)]):true;const evidenceReady=bp?ws.evidence.length>=bp.minEvidence:true;
 const gate=useMemo(()=>({fieldReady,checkReady,evidenceReady,ready:fieldReady&&checkReady&&evidenceReady}),[fieldReady,checkReady,evidenceReady]);
 if(!bp)return null;
 const setValue=(key:string,value:string)=>dispatch({type:'WORKSHOP_VALUE',id:machine.code,payload:{key,value}});
 const toggleCheck=(i:number)=>dispatch({type:'WORKSHOP_CHECK',id:machine.code,payload:{key:String(i),value:!ws.checks[String(i)]}});
 const addEvidence=()=>{if(!eTitle.trim())return;dispatch({type:'WORKSHOP_EVIDENCE_ADD',id:machine.code,payload:{id:`ev-${Date.now()}`,type:eType,title:eTitle.trim(),source:eSource.trim(),notes:eNotes.trim(),createdAt:now(),mode:state.mode}});setETitle('');setESource('');setENotes('')};
 return <section className="workbenchShell section"><div className="workbenchTop"><div><span className="eyebrow">MISSION WORKBENCH｜实操任务台</span><h2>{bp.mission}</h2><p>{bp.brief}</p></div><div className={`readinessSeal ${gate.ready?'ready':''}`}><b>{gate.ready?'READY':'IN PROGRESS'}</b><span>{bp.accent}</span></div></div>
 {reviewSignals.length>0&&<div className="reviewSignalGrid section">{reviewSignals.map(([label,value])=><div className="reviewSignal" key={label}><span>{label}</span><b>{value}</b></div>)}</div>}<div className="workbenchGrid"><div className="missionPanel"><div className="panelHead"><b>任务输入</b><span>{required.filter(f=>String(ws.values[f.key]||'').trim()).length}/{required.length} 必填</span></div>{Object.values(seed).some(Boolean)&&<div className="upstreamFlow"><b>上游自动带入</b><span>{Object.entries(seed).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' · ')}</span></div>}<div className="missionFields">{bp.fields.map(f=><label className="missionField" key={f.key}><span>{f.label}{f.required&&<em>*</em>}</span>{f.type==='textarea'?<textarea rows={3} value={ws.values[f.key]||''} placeholder={f.placeholder} onChange={e=>setValue(f.key,e.target.value)}/>:f.type==='select'?<select value={ws.values[f.key]||''} onChange={e=>setValue(f.key,e.target.value)}><option value="">请选择</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type==='number'?'number':'text'} value={ws.values[f.key]||''} placeholder={f.placeholder} onChange={e=>setValue(f.key,e.target.value)}/>} {f.hint&&<small>{f.hint}</small>}</label>)}</div><label className="missionField"><span>工作备注</span><textarea rows={3} value={ws.notes} onChange={e=>dispatch({type:'WORKSHOP_NOTE',id:machine.code,value:e.target.value})} placeholder="记录判断、待核验点、讲师反馈…"/></label></div>
 <div className="qualityPanel"><div className="panelHead"><b>质量闸门</b><span>{bp.checks.filter((_,i)=>ws.checks[String(i)]).length}/{bp.checks.length}</span></div><div className="qualityList">{bp.checks.map((x,i)=><button key={x} className={`qualityCheck ${ws.checks[String(i)]?'checked':''}`} onClick={()=>toggleCheck(i)}><i>{ws.checks[String(i)]?'✓':''}</i><span>{x}</span></button>)}</div><div className="signalCard"><span>完成信号</span><b>{bp.signal}</b></div></div>
 <div className="evidencePanel"><div className="panelHead"><b>证据台账</b><span>{ws.evidence.length}/{bp.minEvidence} 最低</span></div><div className="evidenceComposer"><div className="evidenceComposerRow"><select value={eType} onChange={e=>setEType(e.target.value as WorkspaceEvidence['type'])}>{['截图','链接','数据','说明','文件'].map(x=><option key={x}>{x}</option>)}</select><input value={eTitle} onChange={e=>setETitle(e.target.value)} placeholder="证据标题*"/></div><input value={eSource} onChange={e=>setESource(e.target.value)} placeholder="来源 / URL / 文件名"/><textarea rows={2} value={eNotes} onChange={e=>setENotes(e.target.value)} placeholder="这条证据证明什么？"/><button className="btn" onClick={addEvidence}>加入证据</button></div><div className="evidenceLedger">{ws.evidence.length===0?<p className="emptyHint">尚无证据。真实操作优先；模拟必须保留模式标识。</p>:ws.evidence.map(ev=><div className="evidenceTicket" key={ev.id}><div><span className="status info">{ev.type}</span><b>{ev.title}</b></div><small>{ev.mode==='real'?'真实':ev.mode==='mixed'?'混合':'模拟'} · {new Date(ev.createdAt).toLocaleString()}</small>{ev.source&&<p>{ev.source}</p>}{ev.notes&&<p className="subtle">{ev.notes}</p>}<button onClick={()=>dispatch({type:'WORKSHOP_EVIDENCE_REMOVE',id:machine.code,value:ev.id})}>移除</button></div>)}</div></div></div>
 <div className="workbenchFooter"><div className="gateStrip"><span className={fieldReady?'pass':''}>输入完整</span><span className={checkReady?'pass':''}>质量闸门</span><span className={evidenceReady?'pass':''}>证据最低量</span><span className={current==='COMPLETE'?'pass':''}>状态机完成</span></div><div className="toolbar">{machine.tools.map(t=><Link className="btn secondary" key={t} to={`/t01/tools/${t.toLowerCase()}`}>{t} 工具</Link>)}{machine.results.map(r=><Link className="btn secondary" key={r} to="/t01/results">{r} 经营档案</Link>)}</div></div></section>
}
