export type WorkshopField={key:string;label:string;type?:'text'|'select'|'textarea'|'number';placeholder?:string;options?:string[];required?:boolean;hint?:string};
export type WorkshopBlueprint={mission:string;brief:string;fields:WorkshopField[];checks:string[];minEvidence:number;signal:string;accent:string};
export const workshopBlueprints:Record<string,WorkshopBlueprint>={
'T01-W01':{mission:'锁定第一条可执行 TikTok 经营路线',brief:'把站点、主体/店型、履约和未来7天动作放进同一张启动桌面。',accent:'路线决策',minEvidence:1,signal:'结果不是“最优市场”，而是一条条件成立、缺口透明、可以马上开始的路线。',fields:[{key:'market',label:'首站/站点',placeholder:'例如：US / UK / MY',required:true},{key:'entity',label:'主体与店型状态',type:'select',options:['可执行','需补条件','待核验'],required:true},{key:'fulfillment',label:'首发履约路径',type:'select',options:['中国直发','本地履约','海外仓','待核验'],required:true},{key:'actions',label:'未来7天最先完成的3个动作',type:'textarea',placeholder:'1. …\n2. …\n3. …',required:true}],checks:['站点准入有来源和核验日期','主体/店型没有被假设为已具备','履约路径与库存位置一致','每个关键缺口都有下一步']},
'T01-W02':{mission:'把 TikTok Shop 配到可经营状态',brief:'不背菜单，按经营任务定位当前后台入口，并记录真实可执行/受限状态。',accent:'经营就绪',minEvidence:2,signal:'至少7类经营任务能独立定位，未完成项有责任人与下一步。',fields:[{key:'productPath',label:'商品任务当前入口',placeholder:'Products → …',required:true},{key:'orderPath',label:'订单任务当前入口',placeholder:'Orders → …',required:true},{key:'affiliatePath',label:'Affiliate 当前入口',placeholder:'Affiliate → …',required:true},{key:'restricted',label:'当前受限能力/权限',type:'textarea',placeholder:'KYC、角色权限、审核等'}],checks:['仓库/配送状态已检查','退货/通知设置已检查','权限角色已检查','受限能力没有伪造成“配置成功”']},
'T01-W03':{mission:'从候选SKU中选出首批主测商品',brief:'信号、单位经济账和风险必须一起看，任何高销量信号都不能覆盖合规阻断。',accent:'SKU 决策',minEvidence:2,signal:'每个主测SKU都有验证假设、停止条件和证据时间窗。',fields:[{key:'sku',label:'主测SKU',placeholder:'SKU / 商品名',required:true},{key:'signals',label:'最关键的2类以上有效信号',type:'textarea',required:true},{key:'unitContribution',label:'预计单位贡献',type:'number',placeholder:'金额',required:true},{key:'stop',label:'停止条件',type:'textarea',placeholder:'达到什么条件就停止继续测试',required:true}],checks:['信号来自统一时间窗','GMV没有被当作利润','合规/IP/履约风险已过闸门','测试假设能被后续内容或销售数据验证']},
'T01-W04':{mission:'把一个商品完整送到可发布/可审核状态',brief:'类目、SKU、文案、素材、价格库存配送和前台QA必须形成一条连续发布链。',accent:'Listing 上架',minEvidence:2,signal:'至少一个 Listing 能提交审核；不能真实提交时完整记录模拟链路。',fields:[{key:'sku',label:'本次上架SKU',required:true},{key:'category',label:'类目/资格状态',type:'select',options:['通过','需补资质','待核验'],required:true},{key:'pdp',label:'PDP前台QA结论',type:'textarea',placeholder:'标题、变体、价格、配送、素材…'},{key:'review',label:'提交/审核状态',type:'select',options:['Draft','Ready to submit','Reviewing','Needs attention','Live','模拟完成'],required:true}],checks:['类目与商品真实匹配','变体属于同一真实商品','文案没有堆词/导流/无法证明宣称','素材未被AI改变商品事实','价格库存配送与经济账一致','移动端前台QA已完成']},
'T01-W05':{mission:'完成第一批可发布 TikTok 商业内容',brief:'从可比案例到选题、脚本、镜头和成片，不把“看懂内容”当成“会做内容”。',accent:'内容实验室',minEvidence:2,signal:'至少形成一条可发布成片，并能解释它的 Hook→Demo→Proof→Offer→CTA。',fields:[{key:'sku',label:'对应SKU',required:true},{key:'angle',label:'核心内容角度',placeholder:'场景/问题/欲望/证明…',required:true},{key:'hook',label:'首3秒 Hook',required:true},{key:'proof',label:'关键 Proof/证明',type:'textarea',required:true},{key:'asset',label:'成片/素材位置',placeholder:'文件名/链接/编号'}],checks:['案例可追溯且可比','选题与商品事实一致','脚本能直接拍摄/生成','商品链接/商业披露已考虑','AI辅助未改变商品事实']},
'T01-W06':{mission:'发布并形成第一轮内容迭代判断',brief:'把“发出去”继续推进到商品曝光、点击、订单、GMV和下一版动作。',accent:'发布与迭代',minEvidence:2,signal:'每条测试内容至少留下变量、观察窗、商业指标和下一版动作。',fields:[{key:'video',label:'视频编号/链接',required:true},{key:'variable',label:'本轮只改变的核心变量',required:true},{key:'ctr',label:'CTR',type:'number',placeholder:'%'},{key:'ctor',label:'CTOR',type:'number',placeholder:'%'},{key:'next',label:'下一版动作',type:'textarea',required:true}],checks:['商品挂载状态已检查','观察窗/最小数据已定义','没有只用播放量下结论','下一版只改变可解释变量']},
'T01-W07':{mission:'跑完第一次 Creator / Affiliate 开发',brief:'搜索、筛选、合作配置、邀约和跟进在同一张开发桌面里闭环。',accent:'达人开发',minEvidence:2,signal:'不是“列了达人名单”，而是有优先级、合作方式、邀约状态和下一步。',fields:[{key:'pool',label:'候选Creator数量',type:'number',required:true},{key:'priority',label:'A档Creator数量',type:'number',required:true},{key:'collab',label:'主合作方式',type:'select',options:['Open Collaboration','Target Collaboration','混合'],required:true},{key:'outreach',label:'首轮邀约/跟进结果',type:'textarea',required:true}],checks:['筛选不是只看粉丝量','佣金不突破SKU经济边界','样品状态和成本可追踪','每个A档Creator有明确匹配理由']},
'T01-W08':{mission:'完成 GMV Max 基础启动与结果判断',brief:'先过广告就绪闸门，再设置对象、模式/ROI、预算和素材，并正确理解总渠道归因。',accent:'GMV Max',minEvidence:2,signal:'能解释为什么现在投/不投，以及 Total ROI 为什么不能直接等于纯付费增量。',fields:[{key:'type',label:'Campaign Type',type:'select',options:['Product','LIVE'],required:true},{key:'object',label:'推广对象',required:true},{key:'mode',label:'模式/Target ROI',placeholder:'Target ROI / Max Delivery',required:true},{key:'budget',label:'预算',type:'number',required:true},{key:'decision',label:'当前动作判断',type:'select',options:['继续','暂停','补素材','换商品','调整目标','需核验'],required:true}],checks:['Primary Ad Account已确认','商品/PDP/库存可承接流量','素材供给满足启动条件','经济边界与停止条件明确','Total ROI按总渠道归因理解']},
'T01-W09':{mission:'完成一次可复盘的 TikTok LIVE 成交演练',brief:'把商品Pin、开场、Demo、Proof、Offer、互动和CTA做成一条可执行导演流程。',accent:'LIVE 导演台',minEvidence:1,signal:'至少完成一个完整销售循环，并能根据CTR/CTOR/GMV判断断点。',fields:[{key:'sku',label:'直播主商品',required:true},{key:'offer',label:'核心 Offer',required:true},{key:'cta',label:'主要 CTA',required:true},{key:'breakpoint',label:'本轮最大断点/问题',type:'textarea'}],checks:['商品顺序/Pin已设计','开场不空讲品牌','Demo和Proof可执行','Offer与库存/利润一致','复盘不是只看观看人数']},
'T01-W10':{mission:'在订单沙盘中处理履约与异常',brief:'从正常订单到Tracking异常、退款退货和Shop Health影响，按真实后台动作完成。',accent:'订单沙盘',minEvidence:2,signal:'能在SLA内选择正确动作，并说明对VTR/LDR/OTDR/SFCR或健康度的影响。',fields:[{key:'case',label:'本次订单/异常案例',required:true},{key:'shipping',label:'Shipping Type',required:true},{key:'action',label:'处理动作',type:'textarea',required:true},{key:'health',label:'可能影响的健康/履约指标',type:'textarea'}],checks:['订单状态与动作匹配','Tracking/LSP信息已核对','客服沟通与后台动作一致','退款/损失已记录','指标影响没有用旧阈值硬判断']},
'T01-W11':{mission:'把第一轮经营数据变成未来30天动作',brief:'从漏斗和利润找到主瓶颈，再形成 P0/P1/P2 的下一轮经营计划。',accent:'经营复盘',minEvidence:2,signal:'不是“总结感想”，而是SKU去留、增长动作、负责人、预期信号和复盘日期。',fields:[{key:'bottleneck',label:'当前最大经营瓶颈',type:'textarea',required:true},{key:'p0',label:'P0 动作',type:'textarea',required:true},{key:'p1',label:'P1 动作',type:'textarea',required:true},{key:'reviewDate',label:'下一次复盘日期',placeholder:'YYYY-MM-DD',required:true}],checks:['数据入口/周期一致','GMV、结算、利润已区分','SKU有明确继续/停止判断','动作有负责人/时间/预期信号']}
};
